-- Enable the pgvector extension if not already present
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    telegram_id VARCHAR(50) UNIQUE NULL,
    preferred_language VARCHAR(16) NOT NULL DEFAULT 'en-US',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Idempotent column add for existing deployments
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(16) NOT NULL DEFAULT 'en-US';

-- 2. User Medical Records Metadata
CREATE TABLE IF NOT EXISTS user_medical_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    file_type VARCHAR(50) NOT NULL,  -- e.g., 'pdf', 'jpeg', 'physician_note'
    extracted_summary TEXT,           -- Summary generated by MedGemma / Gemini
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. User Record Embeddings Table
-- Dimension is 768 for gemini text-embedding-004
CREATE TABLE IF NOT EXISTS user_record_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    record_id UUID REFERENCES user_medical_records(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    chunk_index INT NOT NULL,
    chunk_content TEXT NOT NULL,
    embedding vector(768) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- HNSW Vector Similarity Index for User Record Embeddings
CREATE INDEX IF NOT EXISTS idx_user_record_embeddings_vector 
ON user_record_embeddings 
USING hnsw (embedding vector_cosine_ops);

-- Index user_id for fast filtering on specific users
CREATE INDEX IF NOT EXISTS idx_user_record_embeddings_user_id 
ON user_record_embeddings(user_id);


-- 4. General Medical Knowledge Base
CREATE TABLE IF NOT EXISTS general_medical_knowledge (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    disease_category VARCHAR(100) NOT NULL,
    source_title VARCHAR(255) NOT NULL,
    chunk_content TEXT NOT NULL,
    embedding vector(768) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- HNSW Vector Similarity Index for General Medical Knowledge
CREATE INDEX IF NOT EXISTS idx_general_kb_vector 
ON general_medical_knowledge 
USING hnsw (embedding vector_cosine_ops);
